sudo: false
language: node_js
node_js:
- '10'
install: false
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: node tools/npm.js && npm publish
  on:
    branch: master
env:
  global:
  - secure: cUPRyDNLimw+IRgr8OIzpEKB7jgsMF1x3eOvNgPkLGoGZT8kFkT6DLjp4dwxRRmahBqB0mCWD9DCsSUJxZW47XVN6MnoOnrwgSHufNHDjnCTbb8BUCqkAJdj0kd+Qpw+zqbua+yFXyoKCYLWtqXWi7EamThcGIf2OyLF+NMC/3CQUuOngElZG6s9Ctu5Y6PaN6rGuTZjmk81wJy3xoVtDBl4k/0YPmzLdNJ+fsrkMkHv0iwEElYvz65PMJNOK/7qcR5yXXuP7ZqcY1qzYkev1h8lxr1OUbPtAZlQsxHEy0ho758UVcZ0h3DHuJGt8A5zygFZJxlTJVQ+ENGPLXEyiF7nilyHfl267f6NYKy8vOqIfTFLQHGAK12OI1ullyGl+kpF+U9nark3trMLyYCZP57iR3P1QEc83nN+PAAB3WB8xSzB0vMfP45y+8i0sv3vhFcL/Htxi3k8SRV4ZRnl5C70d/hrWKIE0KF8PxwHyfjJPQ+xkeazJ8y946Ex3LojoCyX6Y0IIki3jLelveiSMU6WWsgONqhCBw4Up3mMZM/JGSrnZe0HTyeJyxrkWm7kQVV2Zz/0PGEW6D8C9nvXiJ1dGD8oyTfAQZ1iMUzW2/SfZl3JwekWDR87YaO31u8lLVtK3VG5P4tNz5vnsvq9z1NZSnFFreUaWPan20+9b3A=
  - secure: Nn9mAYPW6ddb8okjHbzCzPsLBYP+E6mN3tQbtbpBedcRAfCjL7VHyoxWnBi1jFCJqCBqo96eYqhQz46wr7kFULbRZUjxM1ua1TWR+P1DDqAizAhzTTNpbaEtk1WaMweDB/Pni+9VZyP/YxXnNqo2BShwLF18ZDSl5h3+IvIe0F3YuQ0osedXWDzi4Me63emLzo+lKMthZvA/WOcJ7b5VQxVPM8pCTh+nG0z8nN393Ce7hdmv9/KcRPCQj3ugfgSPffqMUm05ViJjNv5FABHNsNftVJoa0Yeig3nDirbjBoQhz/dD2V5Et4nNCh48PRN5Ev0Le13VIHadzAl/i14bho5sSpB3gXOkbxjDxLSOKRDPYSoshws/1n4tcBKgsv+MUPjVaCQwK34JKbvFsgsGcPHychDH9Xw7aBkmGHR9aXctD3I3RMEc+GB+NovK/Ogkx10UOdKyPWQvGutM2R7b5JwyVmJ96I6Il9CXZiSvFrSIWuxWQazhDC4PB6lyd5xzLUiT+BC5zNAe5+1WxBxiXZv+Fq/i9ZEP/pwLJ79DNd6bso2BgE6MtWWBlYEZpkuKLW4E8LTDv+eI5Sw1HAQ8pK+2/iYLf8QWTfU2tkAunxksoFlbZb5CPvxTRkalH9p5Wv+v3khzlY6Yk5Sb0osJvFJVNfKERUVoWTMXOEzKc5g=
