sudo: false
language: node_js
node_js:
- '10'
install: false
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: node tools/npm.js && npm publish
  on:
    branch: master
env:
  global:
  - secure: Wj0hEv9MtZsgTPrKOKr93CBgDCWnifjDljnQapGyUBOaBH7xj/zQZJNsPE/faWi8+FGtgoHyFwaRmqXkLnxYHC1pxzhb58csLjGmSBaGV8WHk87fazuBHmx1L4RKvNV1YKw5LQ6eV1JiTyD+Xi0ARX+uOSGv8fbflPmzhhF81Ue6zr+7CkxlqwhzBTpG8tXEevAR2k+L9+KcTS/RQJ8LjoKVj07fATr75dqW0o0Mg3ktsgIGOsu7owruk/Gi2K2wkzKpqj7Idk+otnn6jg8cOtLH8CyPxqV/yTpgbvjYrzHquSYLZT6eb5m8Af9VkQ1QnOH+MyDegLrq9acgPHU3jDI4U394SFnZADmCTmeD6ivQ7jWYyj3X+vy4dNrOqbjz6DSrhqR60ytIYUfptex9ks/zaVHYlN3vmZKhJ/KC8vaOUy5EySzqBj1C63oMUO/GL522ZpMBesaOdnYVDqqOWBZzyoLXIlKs4F489rMwpGYRgcj4BLzbcHd9CuEr8kufi3biGJnqrwnNvNxEsE4c3ypFKbxT6WJHzE2ksxdDhIHJAikWwAQfLUoc+UR5qJkMYKBMb9XvkEVdMMTVMo2JLCsJfNunMkyGLVvrYNTmWzlFcb1dEJLYe3P5fiy0IEnyE4GsHRF7+6q+qdLfjq9TpRcouCGEx+fnYdxKj8X9p+o=
  - secure: tkcP++0Y4+EP07t9INyNqWg8HMuxdV4OBUaz56AFZ/zSXfxA9EhiUN8rav3u7z4dW3RUi26c6gwz7hcWDWgcUY9t+QOpSJG9RemukbApCZ9Rmgzw93dd9yX93gV+j8wehbk19Se9DD6DcdR0lcvarMHGK7MWcvSjro/OeuQj+iSH7ZEvnjgkYu9OFNaxuPkyzhOo5RFw41iOI+hWV3DF18H+n9XsOaDILzEFIdsnAOLRKejRWUUU1VuqqDatb0Yi8fBSSaQchP+PCioUes8rFDtiaGWFAu9KTaDKSwd7FXlrlWAviPvYhzrAvVlXcI0eT/4iQCcPmcSoev4qoEN1FDPxXeNpbkduKK0t3+Vfsx8Pgko2OWw+sO9ijwr55CEnjtrMgT7PLaPYC21o9ytJasok1E3oCBmj7T+mYWM55k0heO5KflUNUKJhCesP8RJ62Q9B4IompNeUX1Acl4H2805An9N5VZ7mkv3NDbUX5mlBRRhQZDy9NieibBhoYOWr/OjBGm4JZvmo1GvrzBU6OTQD6UFRyV/8h1gldX9xkzEKUz13Jeqfd3ZOElMr5G5+T+cteZYBtcsh3DsuF3nCx/94hXcjnoSVq8noRgfST47ROSBJQi8yZJKi9FIxN4jrla0fOZBjWunTqGoz8b8ysQffZsxYoMibCW+zfJqbY1E=
