sudo: false
language: node_js
node_js:
- '10'
install: false
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: node tools/npm.js && npm publish
  on:
    branch: master
env:
  global:
  - secure: jKkQraXIxcdVANd1uzWBgiwCbTikRtMoGvAy7Vl0i9eaNwUzBnCT3rFuJgGQGAmMm5gkalgCAo/RiPcY7NM54Qfm/6iTP7R1owwNjNCDdYitKHyt8YzZfHYN44lClU5fPUyA1VlZWtcCalu1qP3RTr2sVVCaP4pZu4Rg6OiaWesE13YZbzLHYmrwDH8y7VyzLTO4r7h814LkGuFsVJbcNgvBd1V2Khlx7x3r4MWW9/yNdr76+d4dZPZ3A6dxbo5WtSJr5/TlkdhKdu8iHjFknz4YfWtrLZ1vY1e+mKD9hBx32jV6aZUjUC+j2197if3B56SGqJON3ySVfFw28Xwm0tq+KsaCDMvQx6z7aROt8E/Uv18HZneD3sHrDCmIP3G1/nY/9LykxO2pE7BcEQTjjFMfnSovoK9pQcENJDagZjjGE36DNI1cBh25jbw0O2oaip+hLh4pbhFkHMZ7tVYCcb+o3UAk2Vw2gFzefGWrHlIRJmI46mnV5aB++PVpJ6tO4h48XyeDCihZkrYIA5dibtt1283/gX3RFe1G9Or3D+5SGGJHh4vR1UMIJAKgRDp7P/7MUeaSzhXguQm2yO4LB4ff2M571OT4hURnzqgbWHF2sS2yi/zDZuPqnum/QOh8dTXO6d7M+hYBVOaKCBK9IXIbgKpyJ/fvay3txoCT6NQ=
  - secure: WjfeaPj/5p6V6V+YyRilBrzWWA2G3sg6wpJTBCOHsa2e5Gr6wUc8uAWUVGWO7G4Rc3Y5HJJRRL3YBVdp+49oGp4tIIfEXxtL7MJolhig8X3GwCVZI5nzJ8Jx5clVowQK4Rl3TM10EPq/itBLH70dPiOzCRUenuCtBgqIGqjBLPuMMm9xc5U0V33qNgUjyjbEfY2sHVzYX+8Sgm0AOcyriJDYEADJABm19GUpS8SISuxX1fx1+Wg5Kd3IMblt8u54Q2cfKsZOo6hPCd5l12mXnkfaQR2PKgEKe/YoG/+LilZaPrNAGaobHFcr8LPfS6eaHhuaynhnfjV7EJ9b0wH78XUQOb0pzLR0n3mjuwg6dPrbREqW+SYsYmKCTSjBo4hsBs05NCeklfk0UVBgEDsXGWSflLG1PZ8dnB0VoepXXxTgGvCXKv6/Mq+my0vWC1VQTUXDBNYEL4D6sQq7VsysvfhXAa5jZOgV3aSfSmCJzu8HUbgNXGrQL0uNNT+wttrf2CVsSySkqYq75tQ1n3FUKuGm5Ao7XTZiRFn3QHIIDGCKW4JlKLlbLz5aaoUSp6M0TK3uD3zz+oqGXRK6FyA5UmNknmsSHJg/9agXPaRuff84DAhgIaZwbe4OaRJxtvnI2FjtpsSO0jAs1PyZbCkSDQTvx3rV3bLAAjXNQ5Xd19U=
