[build]
  # This will be run the site build
  command = "npm run export"
  # This is the directory is publishing to netlify's CDN
  publish = "client/out"
  # functions build directory
  functions = "server/functions"
