[build]
  # This will be run the site build
  command = "npm run netlify"
  # This is the directory is publishing to netlify's CDN
  publish = "client/out"
  # functions build directory
  functions = "dist"
